---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k5-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-nosql
  minReadySeconds: 2 # minimum delay for a pod to be considered available
  strategy:
    type: Recreate # zero downtime updating of pods with new ones
  template:
    metadata:
      labels:
        app: php-nosql
    spec:
      containers:
        - name: k5-web
          image: opencom123/php-nosql:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k5-srv
  labels:
    app: php-nosql
spec:
  type: NodePort
  ports:
    - port: 80 #internal cluster port
      nodePort: 30005 #external port
      protocol: TCP
  selector:
    app: php-nosql
